apiVersion: v1
kind: Service
metadata:
  name: client1
  labels:
    app: client1
  namespace: md
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP
  selector:
    app: client1
