apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
  namespace: md
spec:
  type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
    name: http
    protocol: TCP
  selector:
    app: eurekaserver
