apiVersion: v1
kind: Service
metadata: 
  name: client2service
spec: 
  ports: 
    - 
      nodePort: 30002
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector: 
    app: client2
  type: LoadBalancer

apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    app: client2
  name: client2deployment
spec: 
  replicas: 3
  template: 
    metadata: 
      labels: 
        app: client2
    spec: 
      containers: 
        - 
          image: client2
          imagePullPolicy: IfNotPresent
          name: client2
          ports: 
            - 
              containerPort: 8081
  