apiVersion: v1
kind: Service
metadata:
  name: client2
  labels:
    app: client2
  namespace: md
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    name: http
    protocol: TCP
  selector:
    app: client2
